name: blog-service
on:
  push:
    branches:
      - main

jobs:

  docker-build:
    name: DockerBuildandTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build an image from Dockerfile
        run: |
          docker build . --file Dockerfile --tag blog-service/demo:v1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './src/go.mod'
      - run: go version
#      - uses: actions/checkout@v3
      - name: Unittest
        working-directory: ./src
        run: |
             go test -v ./... -coverprofile=coverage.out 
             go test cover -func coverage.out -o coverage.txt

        